#!/bin/bash

set -e

SCRIPT_DIR=$(dirname "$(realpath $0)")
BASE_DIR=$(realpath "${SCRIPT_DIR}/..")
BIN_DIR="${BASE_DIR}/.bin"

function usage() {
    echo -n \
        "Usage: $(basename "$0") {--full}
Build the site.
"
}


if [ "${1:-}" = "--help" ]; then
    usage
else
    export PATH=${PATH}:${BASE_DIR}/.bin
    if [ "${1:-}" = "--full" ]; then
        npm run build:tailwindcss
    fi
    hugo
fi
