#!/bin/bash

set -e

SCRIPT_DIR=$(dirname "$(realpath $0)")
BASE_DIR=$(realpath "${SCRIPT_DIR}/..")
BIN_DIR="${BASE_DIR}/.bin"

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run the dev server.
"
}


if [ "${1:-}" = "--help" ]; then
    usage
else
    export PATH=${PATH}:${BIN_DIR}
    npm run dev
fi
